Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2019-11, with the labels that each got.

#217 Disable proxy tests on Python 2.7
  lib/inputstreamhelper/__init__.py
  test/test_proxy.py
Labels: testing

#207 Add InputStream Helper information to logs
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
Labels: enhancement

#216 Support undetected version
  lib/inputstreamhelper/__init__.py
Labels: bug

#221 Assorted fixes (needed by autoanswer)
  .gitignore
  .pylintrc
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  test/xbmcgui.py
Labels: enhancement

#198 Move imports to where they are being used
  lib/inputstreamhelper/__init__.py
Labels: enhancement

#193 backup and local rollback
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
  lib/inputstreamhelper/config.py
  lib/inputstreamhelper/kodiutils.py
  resources/language/resource.language.en_gb/strings.po
  resources/settings.xml
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: enhancement

#222 Assorted changes
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodehelper.py
Labels: enhancement

#219 Implement progress bar for extraction
  .pylintrc
  lib/inputstreamhelper/__init__.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  test/xbmc.py
  test/xbmcgui.py
Labels: arm, enhancement

#227 Convert subprocess output to unicode
  lib/inputstreamhelper/__init__.py
Labels: arm, bug

#225 Use LANG=C for subprocesses
  lib/inputstreamhelper/__init__.py
Labels: bug, invalid

#224 support paths with spaces when calculating Chrome OS losetup offset
  lib/inputstreamhelper/__init__.py
Labels: arm, bug

#230 Add Python 3.5 testing support
  .travis.yml
  Makefile
  tox.ini
Labels: testing

#231 Add Croatian translation
  resources/language/resource.language.hr_hr/strings.po
Labels: translations

#232 Fix formatting
  lib/inputstreamhelper/__init__.py
Labels: bug

#233 Remove id from settings entries
  resources/settings.xml
Labels: bug
