Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2019-12, with the labels that each got.

#234 Translation JP/KR
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
Labels: translations

#236 Port new kodiutils changes and stubs
  .github/codecov.yml
  .gitignore
  .pylintrc
  .travis.yml
  Makefile
  default.py
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  test/test_proxy.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: testing

#238 Added Hungarian language
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#239 Fix docstrings
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
  lib/inputstreamhelper/config.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodehelper.py
Labels: enhancement

#208 Add Widevine version as built-in
  lib/inputstreamhelper/__init__.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: android, enhancement

#235 Updated german translation
  resources/language/resource.language.de_de/strings.po
Labels: translations

#237 Change rollback to restore.
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: translations

#243 Report pylint useless suppressions
  Makefile
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodehelper.py
  test/test_ishelper_android_arm.py
  test/test_ishelper_linux_arm.py
  test/test_ishelper_linux_x64.py
  test/test_ishelper_macos_x64.py
  test/test_ishelper_windows_x64.py
  test/test_proxy.py
Labels: testing
