Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2019-09, with the labels that each got.

#145 move releases to readme
  README.md
Labels: enhancement

#150 Clean up coverage/codecov config
  .coveragerc
  .github/codecov.yml
  .travis.yml
Labels: testing

#139 Add About category to settings page.
  addon.py
  lib/config.py
  lib/inputstreamhelper.py
  resources/language/resource.language.en_gb/strings.po
  resources/settings.xml
  test/test_api.py
  test/xbmcgui.py
Labels: enhancement

#144 simplify entry point to speed up loading time
  addon.py
  lib/api.py
Labels: enhancement

#154 Restructure code for new release
  .gitignore
  .pylintrc
  .travis.yml
  Makefile
  addon.xml
  default.py
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
  lib/inputstreamhelper/config.py
  test/test_api.py
  tox.ini
Labels: bug

#155 Rename 'About' into 'IS Info'
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  resources/settings.xml
  test/test_api.py
  test/xbmcextra.py
  test/xbmcgui.py
Labels: enhancement

#153 0.4.2 release
  README.md
  addon.xml
Labels: release

#159 Create strings.po
  resources/language/resource.language.fr_fr/strings.po
Labels: enhancement, translations

#160 Update french translation with missing strings
  resources/language/resource.language.fr_fr/strings.po
Labels: enhancement, translations

#161 Implement translation tests
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
Labels: testing, translations

#166 fix visibility in kodi 19
  addon.xml
Labels: enhancement

#164 Assorted fixes to translations and testing
  .pylintrc
  Makefile
  lib/inputstreamhelper/__init__.py
  resources/__init__.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  test/test_api.py
  test/test_ishelper_android_arm.py
  test/test_ishelper_linux_arm.py
  test/test_ishelper_linux_x64.py
  test/test_ishelper_macos_x64.py
  test/test_ishelper_windows_x64.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: testing, translations

#167 Updated Russian translation
  resources/language/resource.language.ru_ru/strings.po
Labels: translations

#169 consciously use unicode
  addon.xml
  default.py
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/unicodehelper.py
Labels: enhancement

#171 Remove kodi-six from tests
  test/kodi_six/__init__.py
  test/kodi_six/utils.py
  test/kodi_six/xbmc.py
  test/kodi_six/xbmcaddon.py
  test/kodi_six/xbmcdrm.py
  test/kodi_six/xbmcgui.py
  test/kodi_six/xbmcplugin.py
  test/kodi_six/xbmcvfs.py
Labels: testing

#172 Backport xbmc fixes, fix coverage
  .github/codecov.yml
  setup.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: testing

#21 Custom path for ARM devices with limited space
  lib/inputstreamhelper/__init__.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  resources/settings.xml
  test/userdata/addon_settings.json
  test/xbmc.py
  test/xbmcgui.py
Labels: arm, bug

#173 Make update frequency configurable.
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/config.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  resources/settings.xml
  test/userdata/addon_settings.json
Labels: enhancement

#175 create all folders in temp path
  Makefile
  lib/inputstreamhelper/__init__.py
  test/xbmc.py
Labels: testing

#176 fix crashes when inputstream addon is missing
  lib/inputstreamhelper/__init__.py
  resources/settings.xml
Labels: bug

#179 update language files
  Makefile
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: testing, translations

#181 Rename "Troubleshooting" to "Expert"
  Makefile
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
  resources/settings.xml
Labels: enhancement

#184 clean userdata except settings
  Makefile
Labels: testing

#188 Translate path and compare before moving
  lib/inputstreamhelper/__init__.py
Labels: bug

#182 Disable all options on Android
  resources/settings.xml
Labels: enhancement

#185 Backport xbmc stubs and avoid writing
  .pylintrc
  test/userdata/addon_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
Labels: testing

#190 Update german translation, including addon.xml
  addon.xml
  resources/language/resource.language.de_de/strings.po
Labels: translations

#194 Italian translation updated
  resources/language/resource.language.it_it/strings.po
Labels: translations

#197 fix new pylint v2.4 tests
  .pylintrc
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
Labels: testing

#195 Update strings.po
  resources/language/resource.language.fr_fr/strings.po
Labels: translations

#199 Fix issue preventing chromeos_version in info
  Makefile
  lib/inputstreamhelper/__init__.py
Labels: arm, bug

#178 0.4.3 release
  Makefile
  README.md
  addon.xml
Labels: release

#205 Remove Widevine information on Android
  lib/inputstreamhelper/__init__.py
  requirements.txt
  resources/language/resource.language.nl_nl/strings.po
Labels: android, enhancement
