Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2019-08, with the labels that each got.

#71 Replace requests and urllib3 with urllib/urllib2
  addon.xml
  lib/inputstreamhelper.py
Labels: enhancement

#74 A few more sanity fixes on Travis CI
  .travis.yml
  README.md
  addon.xml
  changelog.txt
  lib/inputstreamhelper.py
  pylintrc
Labels: enhancement

#51 Add proxy support (on-the-fly)
  addon.xml
  lib/inputstreamhelper.py
  resources/language/resource.language.en_gb/strings.po
Labels: enhancement

#75 Remove legacy support
  lib/config.py
  lib/inputstreamhelper.py
Labels: enhancement

#78 Fixes a python "No such file or directory" error
  lib/inputstreamhelper.py
Labels: bug

#81 Support 64-bit kernel with 32-bit userspace
  lib/inputstreamhelper.py
Labels: arm, bug

#83 ModProbe needs to run as shell on some systems
  lib/inputstreamhelper.py
Labels: arm, bug

#30 check widevine support before all checks
  lib/inputstreamhelper.py
Labels: enhancement

#80 Ensure platform.system() is run just once
  lib/inputstreamhelper.py
Labels: enhancement

#84 Select the best ARM image available
  lib/config.py
  lib/inputstreamhelper.py
Labels: enhancement

#82 Add proper progress dialog for extraction
  lib/inputstreamhelper.py
  resources/language/resource.language.en_gb/strings.po
Labels: enhancement

#86 Handle IOError: [Errno 10] No child processes
  lib/inputstreamhelper.py
Labels: bug

#88 Implement preliminary integration tests
  .gitignore
  .travis.yml
  Makefile
  lib/inputstreamhelper.py
  pylintrc
  requirements.txt
  test/kodi_six/__init__.py
  test/kodi_six/utils.py
  test/kodi_six/xbmc.py
  test/kodi_six/xbmcaddon.py
  test/kodi_six/xbmcdrm.py
  test/kodi_six/xbmcgui.py
  test/kodi_six/xbmcplugin.py
  test/kodi_six/xbmcvfs.py
  test/test_ishelper.py
  test/userdata/addon_settings.json
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: enhancement

#34 Make option to disable module visible in GUI
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/settings.xml
Labels: enhancement

#91 Implement settings menu and API
  Makefile
  addon.py
  addon.xml
  lib/inputstreamhelper.py
  resources/language/resource.language.en_gb/strings.po
  resources/settings.xml
Labels: enhancement

#98 Add API for check_inputstream
  addon.py
  test/routing.py
  test/test_ishelper.py
  test/test_routing.py
  test/xbmcaddon.py
Labels: enhancement

#95 directly remove and install Widevine in Kodi CDM dir
  addon.py
  lib/config.py
  lib/inputstreamhelper.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  test/xbmc.py
Labels: bug, enhancement

#96 use local url variable
  lib/inputstreamhelper.py
Labels: enhancement

#99 force bytestring for os.walk
  lib/inputstreamhelper.py
Labels: bug

#97 Dutch translation fixes
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
Labels: enhancement

#100 Use named placeholders for translations and logs
  lib/inputstreamhelper.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
Labels: enhancement

#103 Translate to Dutch and prepare translations
  .gitignore
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
Labels: enhancement

#112 Ensure only a single plugin icon
  addon.py
  addon.xml
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
Labels: bug, routing

#110 Ensure mountpoint is unmounted properly
  lib/inputstreamhelper.py
Labels: arm, bug

#114 Use "(Re)install Widevine CDM" for settings
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
Labels: enhancement, translations

#111 Remove (dangling) symlinks before extraction
  lib/inputstreamhelper.py
Labels: bug, x86

#115 Add platform integration tests
  Makefile
  lib/inputstreamhelper.py
  pylintrc
  test/test_ishelper_lin_arm.py
  test/test_ishelper_lin_x64.py
  test/test_ishelper_mac_x64.py
  test/test_ishelper_win_x64.py
  test/xbmcextra.py
  test/xbmcgui.py
Labels: enhancement

#117 improve Dutch translations
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement, translations

#118 Updated Russian translation
  addon.xml
  resources/language/resource.language.ru_ru/strings.po
Labels: enhancement, translations

#120 Update German translations
  resources/language/resource.language.de_de/strings.po
Labels: enhancement, translations

#126 Swedish translation
  resources/language/resource.language.sv_se/strings.po
Labels: enhancement, translations

#127 Update strings.po, due to minor typo
  resources/language/resource.language.el_gr/strings.po
Labels: enhancement, translations

#121 Updated: Dutch Language
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement, translations

#128 Add coverage support
  .coveragerc
  .gitignore
  .travis.yml
  Makefile
  README.md
  requirements.txt
Labels: enhancement

#125 Small improvements to german translation.
  resources/language/resource.language.de_de/strings.po
Labels: enhancement, translations

#123 Fix various issues found during testing
  .coveragerc
  .gitignore
  .travis.yml
  Makefile
  addon.py
  lib/inputstreamhelper.py
  test/test_ishelper_android_arm.py
  test/test_ishelper_linux_arm.py
  test/test_ishelper_linux_x64.py
  test/test_ishelper_macos_x64.py
  test/test_ishelper_windows_x64.py
  test/test_routing.py
  test/xbmcaddon.py
Labels: arm, enhancement

#134 Small fixes
  .coveragerc
  Makefile
Labels: enhancement

#135 Various coverage improvements
  .travis.yml
  test/test_routing.py
Labels: enhancement

#104 Prepare for v0.4.0 release
  addon.xml
  changelog.txt
Labels: release

#137 More coverage improvements
  .coveragerc
  lib/inputstreamhelper.py
  pylintrc
  test/test_ishelper_android_arm.py
  test/test_ishelper_linux_arm.py
  test/test_ishelper_linux_x64.py
  test/test_ishelper_macos_x64.py
  test/test_ishelper_windows_x64.py
Labels: enhancement

#140 Add more project information
  addon.xml
Labels: enhancement, release

#129 Fix ARM processing in unittest locally
  lib/inputstreamhelper.py
Labels: arm, enhancement
