Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-05, with the labels that each got.

#332 Closes #331
  lib/inputstreamhelper/utils.py
Labels: bug, windows

#340 Don't crash info dialog when Widevine is missing
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: arm, bug

#341 Assorted fixes
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
  tests/userdata/addon_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcgui.py
  tests/xbmcvfs.py
Labels: bug

#334 Support unicode chars in paths
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodes.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
  tests/xbmc.py
Labels: arm, bug

#339 Track real progress of unzip in install_widevine_arm
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.es_es/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ro_ro/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: enhancement

#343 Fix paths
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/widevine/arm.py
Labels: bug

#336 v0.4.7 release
  README.md
  addon.xml
Labels: release

#345 updated hun
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#348 Access the zipped Chrome OS image directly
  .pylintrc
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/arm_chromeos.py
  resources/language/resource.language.en_gb/strings.po
Labels: arm, enhancement, widevine

#349 Fix linting warnings and unicode compatibility
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodes.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/arm_chromeos.py
Labels: bug

#350 Improvements for #348
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/arm_chromeos.py
  resources/language/resource.language.en_gb/strings.po
Labels: enhancement

#353 Handle missing widevine config or unknown latest version in update_widevine
  lib/inputstreamhelper/__init__.py
Labels: enhancement

#356 Various improvements to download
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: enhancement

#360 Changes to last_update
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/widevine/widevine.py
  resources/settings.xml
  tests/userdata/addon_settings.json
Labels: enhancement
