Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-06, with the labels that each got.

#364 Updated hun lang.
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#365 Add missing language strings
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.es_es/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ro_ro/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: translations

#363 Changes to Chrome OS recovery
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/config.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: arm, enhancement

#366 Update Dutch translation
  resources/language/resource.language.nl_nl/strings.po
Labels: translations

#369 libwidevinecdm.so exists twice in CrOS images
  lib/inputstreamhelper/widevine/arm_chromeos.py
Labels: arm, bug, widevine

#367 Update French translation
  resources/language/resource.language.fr_fr/strings.po
Labels: translations

#370 Wait for previous Progress dialog to close
  lib/inputstreamhelper/kodiutils.py
Labels: arm, bug

#373 Fix linting issues
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcgui.py
  tests/xbmcvfs.py
Labels: testing

#374 Fix info screen when IA is not installed
  lib/inputstreamhelper/widevine/widevine.py
Labels: arm, bug

#376 updated russian translation
  resources/language/resource.language.ru_ru/strings.po
Labels: translations

#375 Update german translation for version 0.5.0
  resources/language/resource.language.de_de/strings.po
Labels: translations

#382 GRstrings for 0.5.0
  resources/language/resource.language.el_gr/strings.po
Labels: translations

#379 Optimize file operations
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/arm_chromeos.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: bug, enhancement

#383 Updated hun
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#384 correcteo
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#385 Fix dir in legacy extraction
  lib/inputstreamhelper/widevine/arm.py
Labels: bug

#380 v0.5.0 release
  README.md
  addon.xml
Labels: release

#387 Fix Kodi Addon checker warning
  lib/inputstreamhelper/widevine/arm_chromeos.py
Labels: enhancement

#386 Update jp and kr
  resources/language/resource.language.ja_jp/strings.po
  resources/language/resource.language.ko_kr/strings.po
Labels: translations
