Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-04, with the labels that each got.

#303 Add Romanian translation
  resources/language/resource.language.ro_ro/strings.po
Labels: translations

#302 Prepare restructure
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  resources/settings.xml
Labels: enhancement

#304 Restructure
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/__init__.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: enhancement

#306 Automate Github release
  .github/workflows/release.yml
  Makefile
Labels: enhancement, release

#307 v0.4.5 release
  README.md
  addon.xml
Labels: release

#309 Assorted fixes
  .gitattributes
  lib/inputstreamhelper/config.py
  setup.py
Labels: arm, bug

#310 Improve logging, file operations and Widevine CDM detection
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: enhancement

#312 Don't fail on untranslated strings
  .github/workflows/ci.yml
  Makefile
Labels: testing, translations

#314 Make functions cache values
  lib/inputstreamhelper/utils.py
Labels: enhancement

#313 Cache architecture information
  lib/inputstreamhelper/utils.py
Labels: enhancement

#308 Simplify userspace detection on ARM64
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: arm, bug

#317 Fix overlooked call to log()
  lib/inputstreamhelper/__init__.py
Labels: bug

#316 Fix multi-line text in progress dialog
  lib/inputstreamhelper/kodiutils.py
Labels: bug

#321 Update code example in README.md
  README.md
Labels: documentation

#318 Improve settings behavior for all supported Kodi versions
  resources/settings.xml
Labels: enhancement

#323 Delete arch.cached property in unit tests
  lib/inputstreamhelper/kodiutils.py
  tests/test_ishelper_android_arm.py
  tests/test_ishelper_linux_arm.py
  tests/test_ishelper_linux_x64.py
  tests/test_ishelper_macos_x64.py
  tests/test_ishelper_windows_x64.py
  tests/test_proxy.py
  tests/test_utils.py
Labels: bug

#315 Add a 20 MiB buffer to required disk space
  lib/inputstreamhelper/widevine/arm.py
Labels: enhancement

#326 Use temp path with unicode chars for testing
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  tests/userdata/addon_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
Labels: enhancement

#329 Fix new pylint check
  tests/xbmcgui.py
Labels: testing

#328 v0.4.6 release
  README.md
  addon.xml
Labels: release
