Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-10, with the labels that each got.

#396 Add Hebrew translation
  resources/language/resource.language.he_il/strings.po
Labels: translations

#397 Remove PHASER from ARM HWID list
  lib/inputstreamhelper/config.py
Labels: arm, bug, widevine

#399 Prepare for v0.5.1 release
  README.md
  addon.xml
Labels: release

#400 Log when we download a new ChromeOS ARM image
  lib/inputstreamhelper/widevine/arm.py
Labels: arm, enhancement

#402 Submit releases automatically to Kodi repo
  .github/workflows/release.yml
Labels: enhancement, release

#401 Update Chrome OS ARM hardware id's
  lib/inputstreamhelper/config.py
Labels: arm, enhancement

#405 [python] update xbmc.translatePath() to xbmcvfs
  lib/inputstreamhelper/kodiutils.py
  tests/xbmcvfs.py
Labels: bug
