Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-03, with the labels that each got.

#285 Explain why we need to modify the python library path
  .codecov.yml
  default.py
  lib/inputstreamhelper/api.py
Labels: enhancement

#287 Use explicit relative imports instead of sys.path.append
  default.py
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/api.py
Labels: enhancement

#288 Indicate Py2/3 compatibility
  addon.xml
  setup.py
Labels: enhancement

#291 Restructure the code
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  lib/inputstreamhelper/unicodes.py
  lib/inputstreamhelper/utils.py
Labels: enhancement

#293 Support exporting Kodi 19 Matrix compatible zip package
  Makefile
  addon.xml
Labels: enhancement

#298 Add compatibility for Kodi 19 Python API
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: bug, kodi

#300 Migrate from Travis CI to GitHub CI
  .gitattributes
  .github/codecov.yml
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  Makefile
  codecov.yml
  requirements.txt
  tests/__init__.py
  tests/test_api.py
  tests/test_ishelper_android_arm.py
  tests/test_ishelper_linux_arm.py
  tests/test_ishelper_linux_x64.py
  tests/test_ishelper_macos_x64.py
  tests/test_ishelper_windows_x64.py
  tests/test_proxy.py
  tests/userdata/addon_settings.json
  tests/userdata/global_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcvfs.py
Labels: testing

#301 Add the new CI badge to the README
  README.md
Labels: testing
