Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2020-02, with the labels that each got.

#255 Fix select_dialog function
  lib/inputstreamhelper/kodiutils.py
  test/xbmcgui.py
Labels: bug

#266 Update hr_hr translation
  resources/language/resource.language.hr_hr/strings.po
Labels: translations

#264 Italian updated for 0.4.4
  resources/language/resource.language.it_it/strings.po
Labels: translations

#269 Show unsupported architecture in pop-up
  lib/inputstreamhelper/__init__.py
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sv_se/strings.po
Labels: enhancement

#271 Update strings.po
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#273 Do a cleanup before install…
  lib/inputstreamhelper/__init__.py
Labels: enhancement

#277 Add option to calculate checksum in _http_download()
  lib/inputstreamhelper/__init__.py
  test/xbmcvfs.py
Labels: enhancement

#275 Add a 5 second timeout for chunk download
  lib/inputstreamhelper/__init__.py
Labels: enhancement

#279 Add missing to_unicode
  lib/inputstreamhelper/__init__.py
Labels: arm, bug

#278 Fix rollback installed_version not in list
  lib/inputstreamhelper/__init__.py
Labels: arm, bug

#283 Import kodi_version from kodiutils
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/kodiutils.py
Labels: enhancement

#284 Only rollback if widevine is installed
  lib/inputstreamhelper/__init__.py
Labels: bug
