Repository emilsvennesson/script.module.inputstreamhelper, pull requests merged in 2022-02, with the labels that each got.

#483 Fix tests
  .github/workflows/ci.yml
  .pylintrc
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  tests/checkchromeos.py
Labels: testing

#485 Replace disutils.version.LooseVersion with packaging.version.parse
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: bug

#488 Add Python 3.10 to CI testing
  .github/workflows/ci.yml
Labels: testing

#489 Update croatian language
  addon.xml
  resources/language/resource.language.hr_hr/strings.po
Labels: translations

#487 Improve version checks
  lib/inputstreamhelper/__init__.py
  lib/inputstreamhelper/utils.py
  lib/inputstreamhelper/widevine/arm.py
  lib/inputstreamhelper/widevine/widevine.py
Labels: enhancement

#491 Update Chrome OS Serving builds endpoint
  lib/inputstreamhelper/config.py
  tests/checkchromeos.py
Labels: testing

#492 Improve Chrome OS recovery images check
  tests/checkchromeos.py
Labels: testing
